addtaptest ./libdssanity
addtaptest ./libhashSanity
addtaptest ./libstringsTest
addtaptest ./libsysTest
addtaptest ./libutilTest
addtaptest ./libxdbsanity
addtaptest ./liblogsanity
addtaptest ./libnewtuplebuftest
addtaptest ./libkvstoresanity
addtaptest ./libnstest
addtaptest ./libevaltests
addtaptest ./libcalloutsanity
addtaptest ./libruntimetests
addtaptest ./libbcsanity
addtaptest ./hashtabletests
addtaptest ./libdagsanity
addtaptest ./liblicenseKey
addtaptest ./libdatapagetest
addtaptest ./csvparsertests
addtaptest ./varinttests
subdir libapis
subdir libchildnode
subdir libconfig
subdir libmsg
subdir libudf
