// Copyright 2016 Xcalar, Inc. All rights reserved.
//
// No use, or distribution, of this source code is permitted in any form or
// means without a valid, written license agreement with Xcalar, Inc.
// Please refer to the included "COPYING" file for terms and conditions
// regarding the use and redistribution of this software.
//

#ifndef INTHASHTABLEHOOK_H
#define INTHASHTABLEHOOK_H

//
// Embedded in each value type that uses IntHashTable. Makes IntHashTable
// an "intrusive" data structure (google it). This is in a separate file to
// simplify build dependencies.
//
// Intrusive data structures:
//
// - Avoid spurious memory allocations and heap fragmentation.
// - Preserve referential locality.
// - Provide algorithmic guarantee that insert succeeds.
//
// DO NOT EDIT THIS FILE unless your addition is necessary for *all* consumers.
// Get sign-off from the team on any additions. If your use-case needs
// additional functionality, create a similar, but modified, hash table.
//

struct IntHashTableHook {
    IntHashTableHook *next;
};

#endif  // INTHASHTABLEHOOK_H
