---
- name: Reboot all nodes
  hosts: all
  remote_user: xcalar
  become: yes
  tasks:
    - name: Reboot a slow machine that might have lots of updates to apply
      reboot:
        reboot_timeout: 3600
