---
- hosts: all
  remote_user: pi
  become: True
  vars:
    service_name: xcalar.service
  tasks:
  - name: stop xcalar services
    systemd:
      daemon_reload: yes
      name: "{{ service_name }}"
      state: stopped
  - name: start xcalar services
    systemd:
      daemon_reload: yes
      name: "{{ service_name }}"
      state: started
