# this file was generated by
# _XC2_COMPLETE=source xc2 > doc/env/xc2_complete.sh
# for more see http://click.pocoo.org/5/bashcomplete/
_xc2_completion() {
    COMPREPLY=( $( env COMP_WORDS="${COMP_WORDS[*]}" \
                   COMP_CWORD=$COMP_CWORD \
                   _XC2_COMPLETE=complete $1 ) )
    return 0
}

complete -F _xc2_completion -o default xc2;
