Document: xcalar
Title: Debian xcalar Manual
Author: <insert document author here>
Abstract: This manual describes what xcalar is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xcalar/xcalar.sgml.gz

Format: postscript
Files: /usr/share/doc/xcalar/xcalar.ps.gz

Format: text
Files: /usr/share/doc/xcalar/xcalar.text.gz

Format: HTML
Index: /usr/share/doc/xcalar/html/index.html
Files: /usr/share/doc/xcalar/html/*.html
